DROP TABLE IF EXISTS comment_report_messages;
DROP TABLE IF EXISTS comment_report_threads;
DROP TABLE IF EXISTS comment_likes;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS resource_report_messages;
DROP TABLE IF EXISTS resource_report_threads;
DROP TABLE IF EXISTS contributor_application_appeal_messages;
DROP TABLE IF EXISTS contributor_applications;
DROP TABLE IF EXISTS heritage_resources;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(120) NOT NULL UNIQUE,
    username        VARCHAR(60)  NOT NULL UNIQUE,
    password_hash   VARCHAR(100) NOT NULL,
    role            VARCHAR(20)  NOT NULL DEFAULT 'USER',
    failed_attempts INT          NOT NULL DEFAULT 0,
    locked_until    TIMESTAMP    NULL,
    last_login_at   TIMESTAMP    NULL,
    avatar_url      VARCHAR(500) NULL,
    bio             CLOB         NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE heritage_resources (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(200) NOT NULL,
    title_en       VARCHAR(200),
    category       VARCHAR(60)  NOT NULL,
    period         VARCHAR(100),
    place          VARCHAR(60)  NOT NULL,
    description    CLOB,
    thumbnail      VARCHAR(500),
    copyright      VARCHAR(500),
    tracking_id    VARCHAR(40) UNIQUE,
    status         VARCHAR(20)  NOT NULL DEFAULT 'APPROVED',
    view_count     INT          NOT NULL DEFAULT 0,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_user_id  BIGINT       NULL,
    owner_username VARCHAR(60)  NULL,
    FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id BIGINT      NOT NULL,
    user_id     BIGINT      NOT NULL,
    parent_id   BIGINT      NULL,
    content     CLOB        NOT NULL,
    status      VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP   NULL,
    FOREIGN KEY (resource_id) REFERENCES heritage_resources(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_id) REFERENCES comments(id) ON DELETE CASCADE
);

CREATE TABLE comment_likes (
    comment_id BIGINT    NOT NULL,
    user_id    BIGINT    NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (comment_id, user_id),
    FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE comment_report_threads (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id       BIGINT       NOT NULL,
    reporter_user_id BIGINT       NOT NULL,
    reporter_name    VARCHAR(120) NOT NULL,
    status           VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (comment_id, reporter_user_id),
    FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE,
    FOREIGN KEY (reporter_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE comment_report_messages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id   BIGINT       NOT NULL,
    sender_role VARCHAR(20)  NOT NULL,
    sender_name VARCHAR(120) NOT NULL,
    content     CLOB         NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (thread_id) REFERENCES comment_report_threads(id) ON DELETE CASCADE
);

CREATE TABLE contributor_applications (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT       NOT NULL,
    full_name            VARCHAR(120) NOT NULL,
    expertise_field      VARCHAR(120) NOT NULL,
    motivation_statement CLOB         NOT NULL,
    portfolio_link       VARCHAR(500) NULL,
    attachment_name      VARCHAR(255) NULL,
    attachment_url       VARCHAR(500) NULL,
    status               VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    rejection_comments   CLOB         NULL,
    submitted_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at          TIMESTAMP    NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE contributor_application_appeal_messages (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT       NOT NULL,
    sender_role    VARCHAR(20)  NOT NULL,
    sender_name    VARCHAR(120) NOT NULL,
    content        CLOB         NOT NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (application_id) REFERENCES contributor_applications(id) ON DELETE CASCADE
);

CREATE TABLE resource_report_threads (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id      BIGINT       NOT NULL,
    reporter_user_id BIGINT       NOT NULL,
    reporter_name    VARCHAR(120) NOT NULL,
    status           VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (resource_id, reporter_user_id),
    FOREIGN KEY (resource_id) REFERENCES heritage_resources(id) ON DELETE CASCADE,
    FOREIGN KEY (reporter_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE resource_report_messages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id   BIGINT       NOT NULL,
    sender_role VARCHAR(20)  NOT NULL,
    sender_name VARCHAR(120) NOT NULL,
    content     CLOB         NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (thread_id) REFERENCES resource_report_threads(id) ON DELETE CASCADE
);
