CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(120) NOT NULL UNIQUE,
    username        VARCHAR(60)  NOT NULL UNIQUE,
    password_hash   VARCHAR(100) NOT NULL,
    role            VARCHAR(20)  NOT NULL DEFAULT 'USER',
    failed_attempts INT          NOT NULL DEFAULT 0,
    locked_until    TIMESTAMP    NULL,
    last_login_at   TIMESTAMP    NULL,
    avatar_url      VARCHAR(500) NULL,
    bio             CLOB         NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
